apiVersion: v1
kind: Namespace
metadata:
  name:  custom
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: custom
  name:  customize-container
  labels:
    name:  nginx
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  selector:
    matchLabels:
      name: nginx
  template:
    metadata:
      labels:
        name:  nginx
    spec:
      containers:
      - image:  dogra21703/bookairports
        name:  customize-container
        imagePullPolicy: Always
        resources:
          requests:
            cpu: "20m"
            memory: "55M"
          limits:
            cpu: "40m"
            memory: "110M"
        env:
        - name:  SOHAN
          value:  DOGRA       
        ports:
        - containerPort:  8995
          name:  my-name
        volumeMounts:
        - mountPath: /data
          name: data
      volumes:
        - name: data
          emptyDir: {}
      restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name:  my-service
  namespace: custom
spec:
  selector:
    name:  nginx
  type:  LoadBalancer 
  ports:
  - name:  my-name
    port:  80
    targetPort:  8995
    nodePort: 30078