---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig 


metadata:
  name:  eksctl-test
  region: ap-south-1

nodeGroups:
  - name: ng1-public
    instanceType: t3.micro
    minSize: 2
    maxSize: 20
    desiredCapacity: 4

managedNodeGroups:
  - name: ng2-managed
    instanceType: t3.micro
    minSize: 2
    maxSize: 6
    desiredCapacity: 3
  