apiVersion: v1
kind: Namespace
metadata:
  name:  load-balance
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: load-balance
  labels:
    app: nginx
  namespace: load-balance
spec:
  replicas: 1
  minReadySeconds: 30
  selector:
    matchLabels:
      app: nginx
  template:
    metadata: 
      name: create-container
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx-container
        image: nginx
        imagePullPolicy: Always
        resources:
          requests:
            cpu: "200m"
            memory: "200Mi"
          limits:
            cpu: "200m"
            memory: "200Mi"
        ports:
        - containerPort: 80
        env:
          - name: SOHAN
            value: DOGRA

---
kind: Service
apiVersion: v1
metadata:
  name:  nginx-service
  namespace: load-balance
spec:
  selector:
    app:  nginx
  type:  LoadBalancer 
  ports:
  - name:  nginx-port
    port:  8090
    targetPort:  80