apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-affinity
  namespace: default
  
spec:
  selector:
    matchLabels:
      SOHAN: DOGRA
  replicas: 2
  template:
    metadata:
      name: cont
      labels:
        SOHAN: DOGRA
    spec:
      containers:
      - name: own
        image: nginx
        resources:
          requests:
            cpu: "20m"
            memory: "20M"
          limits:
            cpu: "40m"
            memory: "400M"
        ports:
        - containerPort: 80
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            preference:
              matchExpressions:
              - key: SOHAN
                operator: NotIn
                values:
                - DOGRA
      tolerations:
        - key: key1
          operator: Equal
          value: value1
          effect: NoSchedule

