apiVersion: v1
kind: Pod
metadata:
  name: pod1
  namespace: default
  labels:
    name: pod1
spec:
  containers:
  - name: pod1
    image: nginx
    resources:
    env:
    - name: Sohan
      value: intelligent
    ports:
    - containerPort:  80
      name:  http