apiVersion: v1
kind: Namespace
metadata:
  name:  quota
---
apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: ResourceQuota
  metadata:
    name: pods-high
    namespace: quota 
  spec:
    hard:
      cpu: "200m"
      memory: 200Mi
      pods: "2"
    scopeSelector:
      matchExpressions:
      - operator : In
        scopeName: PriorityClass
        values: ["high"]
- apiVersion: v1
  kind: ResourceQuota
  metadata:
    name: pods-medium
    namespace: quota
  spec:
    hard:
      cpu: "150m"
      memory: 20Mi
      pods: "1"
    scopeSelector:
      matchExpressions:
      - operator : In
        scopeName: PriorityClass
        values: ["medium"]
- apiVersion: v1
  kind: ResourceQuota
  metadata:
    name: pods-low
    namespace: quota
  spec:
    hard:
      cpu: "100m"
      memory: 10Mi
      pods: "1"
    scopeSelector:
      matchExpressions:
      - operator : In
        scopeName: PriorityClass
        values: ["low"]