apiVersion: v1
kind: Namespace
metadata:
  name:  quota-ns
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: ss
  namespace: quota-ns
spec:
  hard:
    requests.cpu: '1'
    requests.memory: 500Mi
    limits.cpu: '2'
    limits.memory: 500Mi
    pods: '2'
    persistentvolumeclaims: '5'
    requests.storage: 5Gi