apiVersion: apps/v1
kind: Deployment
metadata:
  name:  secret-env
  labels:
    name:  env
spec:
  selector:
    matchLabels:
      name: env
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        name:  env
    spec:
      containers:
      - image:  nginx
        name:  nginx-container
        imagePullPolicy: Always
        resources:
          requests:
            cpu: "20m"
            memory: "300Mi"
          limits:
            cpu: "200m"
            memory: "300Mi"
        envFrom:
        - secretRef:
            name: password        
        ports:
        - containerPort:  80
          name:  conf
      restartPolicy: Always
      