
apiVersion: apps/v1
kind: Deployment
metadata:
  name: secret-volume
  namespace: default
  labels:
    name: vol-secret
spec:
  replicas: 2
  minReadySeconds: 30
  selector: 
    matchLabels:
      name: vol-secret
  template:
    metadata:
      name: secret-container
      labels:
        name: vol-secret
    spec:
      containers:
      - name: nginx
        image: nginx
        resources:
          requests:
            cpu: "200m"
            memory: "400Mi"
          limits:
            cpu: "200m"
            memory: "400Mi"
      #This is where we calling the volumes inside a container to get mounted at /mypath folder
        volumeMounts:
          - name:  secret-vol-1
            mountPath:  "/mypath"
            readOnly: true
    #In the below step we are mounting secret as a volumes inside a container
      volumes:
        - name:  secret-vol-1
          secret:
            secretName: conf
